#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCross.Plugins.Ratings.Droid.Resource", IsApplication=false)]

namespace MvvmCross.Plugins.Ratings.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public static int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public static int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f010007
			public static int deselectedRatingResource = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public static int maxRatings = 2130771979;
			
			// aapt resource value: 0x7f010009
			public static int readonlyDeselectedRatingResource = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int readonlySelectedRatingResource = 2130771978;
			
			// aapt resource value: 0x7f010008
			public static int selectedRatingResource = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f020000
			public static int MvvmCrossTagId = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int MvxBindingTagUnique = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public static int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRatingView = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public static int MvxRatingView_deselectedRatingResource = 0;
			
			// aapt resource value: 4
			public static int MvxRatingView_maxRatings = 4;
			
			// aapt resource value: 2
			public static int MvxRatingView_readonlyDeselectedRatingResource = 2;
			
			// aapt resource value: 3
			public static int MvxRatingView_readonlySelectedRatingResource = 3;
			
			// aapt resource value: 1
			public static int MvxRatingView_selectedRatingResource = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
